"""add_vacancies_applications_and_question_fields

Revision ID: 0b8a38b90850
Revises: 282ab4cb9d19
Create Date: 2025-11-26 19:34:03.004625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8a38b90850'
down_revision: Union[str, None] = '282ab4cb9d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('ideal_resume', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('question_type', sa.String(length=50), nullable=False, server_default='text'))
    op.add_column('questions', sa.Column('options', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('difficulty', sa.String(length=20), nullable=False, server_default='medium'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'question_type')
    op.drop_table('applications')
    op.drop_table('vacancies')
    # ### end Alembic commands ###
