"""add_unique_constraint_user_contest_tasks

Revision ID: 289b755d2e05
Revises: 817b4830a4a6
Create Date: 2025-11-27 04:43:20.674805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289b755d2e05'
down_revision: Union[str, None] = '817b4830a4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_contest_tasks_user_id'), 'user_contest_tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_contest_tasks_vacancy_id'), 'user_contest_tasks', ['vacancy_id'], unique=False)
    op.create_unique_constraint('uq_user_vacancy_contest_tasks', 'user_contest_tasks', ['user_id', 'vacancy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_vacancy_contest_tasks', 'user_contest_tasks', type_='unique')
    op.drop_index(op.f('ix_user_contest_tasks_vacancy_id'), table_name='user_contest_tasks')
    op.drop_index(op.f('ix_user_contest_tasks_user_id'), table_name='user_contest_tasks')
    # ### end Alembic commands ###
