"""add_task_solutions_and_execution_fields

Revision ID: 51a5f45afcb4
Revises: 5069c0f26708
Create Date: 2025-11-27 03:02:33.177043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a5f45afcb4'
down_revision: Union[str, None] = '5069c0f26708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_solutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('vacancy_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('solution_code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('executions', sa.Column('task_id', sa.UUID(), nullable=True))
    op.add_column('executions', sa.Column('vacancy_id', sa.UUID(), nullable=True))
    op.add_column('executions', sa.Column('is_submit', sa.Boolean(), nullable=False, server_default='false'))
    op.create_foreign_key(None, 'executions', 'vacancies', ['vacancy_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'executions', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.drop_column('executions', 'is_submit')
    op.drop_column('executions', 'vacancy_id')
    op.drop_column('executions', 'task_id')
    op.drop_table('task_solutions')
    # ### end Alembic commands ###
