"""add_vacancy_id_to_questions

Revision ID: 9d16cdcd1f7f
Revises: 0b8a38b90850
Create Date: 2025-11-26 20:10:28.788256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d16cdcd1f7f'
down_revision: Union[str, None] = '0b8a38b90850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('vacancy_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'questions', 'vacancies', ['vacancy_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'vacancy_id')
    # ### end Alembic commands ###
